export const articles = [
  {
    id: 1,
    title: "Corner King  ",   
    category: "Technique",
    
    date: "12 Jan 2025",
    summary: "Comment arsenal ont pu rendre les coup de pieds arrêté  une arme secrète ?",
    image: "https://res.cloudinary.com/imsyp8wq/image/upload/v1783347613/cornersking_yasser.jpg",
    readTime: "5 min",
    tag: "Populaire",
  },
  {
    id: 2,
    title: "La ligne haute du Barça Un pari vertigineux.",   
    category: "Technique",
    date: "15 Déc 2024",
    summary: "Ce qui se joue derrière cette ligne haute, c'est une philosophie entière du football — héritée du Cruyff.",
    image: "https://res.cloudinary.com/imsyp8wq/image/upload/v1783521108/atletico-barca._xlyvtp.jpg",
    readTime: "4 min",
    tag: "Pratique",   
  },
    
  {
    id: 3,
    title: "Préparation physique : le moteur du footballeur",
    category: "Physique",
    age: "U17",
    date: "8 Jan 2025",
    summary: "Programme complet d'endurance, vitesse et explosivité spécialement conçu pour les jeunes joueurs en développement.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    readTime: "7 min",
    tag: "Nouveau",
  },
  {
    id: 4,
    title: "Tactique collective : lire le jeu avant les autres",
    category: "Tactique",
    age: "Senior",
    date: "3 Jan 2025",
    summary: "Comprendre les systèmes de jeu, la pression collective et le pressing haut pour évoluer vers le football professionnel.",
    image: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&q=80",
    readTime: "9 min",
    tag: "Expert",
  },
  {
    id: 5,
    title: "Mental fort : la performance commence dans la tête",
    category: "Mental",
    age: "U13",
    date: "28 Déc 2024",
    summary: "Techniques de concentration, gestion du stress et confiance en soi pour performer sous pression.",
    image: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=800&q=80",
    readTime: "6 min",
    tag: "Essentiel",
  },
  {
    id: 6,
    title: "Nutrition sportive adaptée aux jeunes joueurs",
    category: "Nutrition",
    age: "U11",
    date: "20 Déc 2024",
    summary: "Plan alimentaire optimal avant/après l'entraînement pour maximiser la récupération et la performance.",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    readTime: "8 min",
    tag: "Santé",
  },
  {
    id: 7,
    title: "Le dribble : l'art de passer entre les jambes",
    category: "Technique",
    age: "U9",
    date: "15 Déc 2024",
    summary: "Exercices progressifs pour maîtriser le dribble en espace réduit et en situation de pression défensive.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
    readTime: "4 min",
    tag: "Pratique",
  },
  {
    id: 2,
    title: "La ligne haute du Barça Un pari vertigineux.",   
    category: "Technique",
    date: "15 Déc 2024",
    summary: "Ce qui se joue derrière cette ligne haute, c'est une philosophie entière du football — héritée du Cruyff.",
    image: "https://res.cloudinary.com/imsyp8wq/image/upload/v1783521108/atletico-barca._xlyvtp.jpg",
    readTime: "4 min",
    tag: "Pratique",   
  },
    


]

export const exercises = [
  {
    id: 1,
    name: "Rondo 4v2",
    level: "Intermédiaire",
    duration: "15 min",
    objective: "Conservation du ballon, pression défensive",
    material: "Ballon, cônes",
    description: "Exercice de possession en infériorité numérique pour développer le jeu en une touche.",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    age: "U13",
    theme: "Jeu collectif",
    type: "field",
  },
  {
    id: 2,
    name: "Passes en triangle",
    level: "Débutant",
    duration: "10 min",
    objective: "Précision des passes courtes",
    material: "Ballon, cônes",
    description: "Développement de la précision de passe et du positionnement des appuis.",
    image: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&q=80",
    age: "U9",
    theme: "Passe",
    type: "field",
  },
  {
    id: 3,
    name: "Tir en mouvement",
    level: "Avancé",
    duration: "20 min",
    objective: "Finition après conduite de balle",
    material: "Ballon, cage, cônes",
    description: "Enchaînement conduite + tir en temps limité pour simuler des situations de match.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    age: "U15",
    theme: "Tir",
    type: "field",
  },
  {
    id: 4,
    name: "Plongeons latéraux gardien",
    level: "Intermédiaire",
    duration: "25 min",
    objective: "Réactivité et placement du gardien",
    material: "Ballon, cage, tapis",
    description: "Série de plongeons latéraux enchaînés avec retour rapide au poteau.",
    image: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=800&q=80",
    age: "U11",
    theme: "Plongeons",
    type: "goalkeeper",
  },
  {
    id: 5,
    name: "Sprint avec changement de direction",
    level: "Avancé",
    duration: "12 min",
    objective: "Vitesse et agilité",
    material: "Cônes, chronomètre",
    description: "Répétitions de sprints courts avec changements directionnels aléatoires.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
    age: "U17",
    theme: "Vitesse",
    type: "field",
  },
  {
    id: 6,
    name: "Relance gardien sous pression",
    level: "Avancé",
    duration: "18 min",
    objective: "Jeu aux pieds du gardien",
    material: "Ballon, cônes",
    description: "Le gardien relance proprement sous pressing adverse, travail de la décision rapide.",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    age: "Senior",
    theme: "Relance",
    type: "goalkeeper",
  },
]

export const coaches = [
  {
    id: 1,
    name: "Mohamed Mana",
    role: "Coach Technique Principal",
    experience: "12 ans",
    diplomes: "CAF A Licence",
    specialite: "Technique & Tactique",
    years: 12,
    initials: "M.M",
    color: "#C8A84B",
  },
  {
    id: 2,
    name: "Samir Amara",
    role: "Préparateur Physique",
    experience: "8 ans",
    diplomes: "CAF Pro Licence",
    specialite: "Préparation Physique",
    years: 8,
    initials: "S.A",
    color: "#E8C86A",
  },
  {
    id: 3,
    name: "Bahim Salaheddine ",
    role: "Coach Gardiens",
    experience: "10 ans",
    diplomes: "2eme Degré + Spéc. GK",
    specialite: "Gardiens de But",
    years: 10,
    initials: "B.S",
    color: "#A8883B",
  },
  {
    id: 4,
    name: "Hakim Hamizi",
    role: "Analyste Vidéo",
    experience: "6 ans",
    diplomes: "CAF A Licence",
    specialite: "Tactique & Analyse",
    years: 6,
    initials: "H.H",
    color: "#D4B55A",
  },
]
